[build]
  base = "frontend"
  publish = "frontend/build"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.22"

[[redirects]]
  from = "/api/*"
  to = "https://arkas-lojistik-backend.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "yarn start"
  port = 3000
  publish = "frontend/build"